### ISSUE TITLE
Annotation are not being attached the service account

### ISSUE THREAD

**Issue by Blunderchips** [aws-observability/helm-charts#113]
Looking at [this value here](https://github.com/aws-observability/helm-charts/blob/29c25f77900f062ecee4e69802e5432b76ed4047/charts/amazon-cloudwatch-observability/values.yaml#L492), it does not seem to be used anywhere in the chart?

For what I can see it is just not used anywhere. Expecting to see it being passed somewhere here:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "amazon-cloudwatch-observability.labels" . | nindent 4}}
  name: {{ template "amazon-cloudwatch-observability.managerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
```

What I am trying to is to attach `eks.amazonaws.com/role-arn` for the manager to use. But I am ending up with the following:

```yaml
Name:                amazon-cloudwatch-observability-controller-manager
Namespace:           amazon-cloudwatch
Labels:              app.kubernetes.io/instance=amazon-cloudwatch-observability
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=amazon-cloudwatch-observability
                     app.kubernetes.io/version=1.0.0
Annotations:         meta.helm.sh/release-name: amazon-cloudwatch-observability
                     meta.helm.sh/release-namespace: amazon-cloudwatch
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>

```
